### ISSUE TITLE
Error on install...

### ISSUE THREAD

**Issue by chcaru** [jbdemonte/node-p7zip#1]
Running node v7.5 (npm 4.1.2) on Windows 10 with an elevated console.

When running: `npm i --save p7zip`

I get the following error from npm

```
Downloading https://github.com/jbdemonte/p7zip/archive/16.02.zip
Decompress 16.02.zip
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: spawn make ENOENT
    at exports._errnoException (util.js:1023:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jbdemonte** [comment]
p7zip is a port of 7za.exe for POSIX systems like Unix (Linux, Solaris, OpenBSD, FreeBSD, Cygwin, AIX, ...), MacOS X and also for BeOS and Amiga.
So, you'll not be able to use it on Windows, I guess you can find some other alternatives.

I'll have a look when I'll have a few time if I can include the support of windows using the  7za.exe
No idea when
